/**
 * Styles for BottleDetailScreen — extracted verbatim (Phase 5, god-file
 * breakup). Pure StyleSheet definitions, no component state.
 */
import { Dimensions, StyleSheet } from 'react-native';
import { colors, spacing, radii } from '../theme/tokens';

// SCREEN_WIDTH is unused (verbatim from the screen file — not introduced
// here; flagged for Phase 6 dead-code cleanup, not fixed in this pass).
const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');
const HERO_HEIGHT = SCREEN_HEIGHT * 0.42;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  scrollContent: {
    paddingTop: 0,
  },
  // ── Hero ──────────────────────────────────────────────────────────────────
  heroContainer: {
    width: '100%',
    height: HERO_HEIGHT,
    position: 'relative',
    overflow: 'hidden',
    marginBottom: spacing(3),
  },
  heroImage: {
    width: '100%',
    height: '100%',
  },
  heroImageFallback: {
    width: '100%',
    height: '100%',
    backgroundColor: '#1A0A06',
  },
  heroBackButton: {
    position: 'absolute',
    left: spacing(2),
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0,0,0,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  heroBadge: {
    position: 'absolute',
    right: spacing(2),
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(0.5),
    backgroundColor: 'rgba(0,0,0,0.5)',
    paddingHorizontal: spacing(1.5),
    paddingVertical: spacing(0.5),
    borderRadius: radii.md,
    zIndex: 10,
  },
  heroBadgeText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.gold,
    letterSpacing: 0.3,
  },
  heroBadgeLowConfidence: {
    backgroundColor: 'rgba(255,152,0,0.18)',
    borderWidth: 1,
    borderColor: 'rgba(255,152,0,0.4)',
  },
  heroBadgeTextLowConfidence: {
    color: colors.warning,
  },
  heroContent: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: spacing(3),
    paddingBottom: spacing(3),
  },
  heroIconFallback: {
    marginBottom: spacing(1.5),
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: `${colors.gold}15`,
    borderWidth: 2,
    borderColor: `${colors.gold}40`,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroBottleName: {
    fontSize: 28,
    fontWeight: '900',
    color: '#fff',
    letterSpacing: -0.3,
    marginBottom: spacing(0.5),
  },
  heroBottleBrand: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.65)',
    fontWeight: '500',
    marginBottom: spacing(2),
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  heroPills: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  heroPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(0.5),
  },
  heroPillText: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.75)',
    fontWeight: '600',
  },
  heroPillDivider: {
    width: 1,
    height: 10,
    backgroundColor: 'rgba(255,255,255,0.2)',
    marginHorizontal: spacing(1.5),
  },
  heroStoryLine: {
    marginTop: spacing(1),
    fontSize: 13,
    lineHeight: 18,
    color: 'rgba(255,255,255,0.82)',
  },
  bodyContent: {
    paddingHorizontal: spacing(3),
  },
  // (kept for any remaining references)
  capturedImageContainer: { display: 'none' },
  capturedImage: { display: 'none' },
  headerBadgeText: { display: 'none' },
  iconContainer: { display: 'none' },
  iconBadge: { display: 'none' },
  bottleName: { display: 'none' },
  bottleBrand: { display: 'none' },
  statsContainer: { display: 'none' },
  statCard: { display: 'none' },
  statValue: { display: 'none' },
  statLabel: { display: 'none' },
  header: { display: 'none' },
  headerBadge: { display: 'none' },
  priceCard: {
    backgroundColor: `${colors.accent}10`,
    borderRadius: radii.lg,
    padding: spacing(2),
    marginBottom: spacing(3),
    borderWidth: 1,
    borderColor: `${colors.accent}30`,
  },
  priceHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(1),
    marginBottom: spacing(1.5),
  },
  priceTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.text,
    flex: 1,
  },
  regionBadge: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.accent,
    backgroundColor: `${colors.accent}20`,
    paddingHorizontal: spacing(1),
    paddingVertical: spacing(0.5),
    borderRadius: radii.sm,
  },
  priceText: {
    fontSize: 18,
    color: colors.text,
    fontWeight: '700',
    marginBottom: spacing(0.5),
  },
  priceDisclaimer: {
    fontSize: 11,
    color: colors.subtext,
    marginTop: spacing(1),
    fontStyle: 'italic',
  },
  serveCard: {
    backgroundColor: colors.card,
    borderRadius: radii.lg,
    padding: spacing(2),
    marginBottom: spacing(3),
    borderWidth: 1,
    borderColor: colors.line,
    gap: spacing(1.5),
  },
  serveCardPremium: {
    backgroundColor: `${colors.gold}10`,
    borderColor: `${colors.gold}35`,
  },
  serveHeader: {
    flexDirection: 'row',
    gap: spacing(2),
    alignItems: 'flex-start',
  },
  serveHeaderCopy: {
    flex: 1,
    gap: spacing(0.5),
  },
  serveEyebrow: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.gold,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  serveTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.text,
  },
  serveSubtitle: {
    fontSize: 13,
    color: colors.subtext,
    lineHeight: 18,
  },
  firstPourBadge: {
    minWidth: 92,
    paddingHorizontal: spacing(1.5),
    paddingVertical: spacing(1),
    borderRadius: radii.md,
    backgroundColor: `${colors.gold}18`,
    borderWidth: 1,
    borderColor: `${colors.gold}30`,
    alignItems: 'flex-start',
  },
  firstPourLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.gold,
    textTransform: 'uppercase',
  },
  firstPourValue: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.text,
    marginTop: spacing(0.25),
  },
  serveWhy: {
    fontSize: 14,
    color: colors.text,
    lineHeight: 21,
  },
  serveModesRail: {
    marginHorizontal: -spacing(2),
  },
  serveModesRailContent: {
    flexDirection: 'row',
    paddingHorizontal: spacing(2),
    paddingBottom: spacing(0.5),
    gap: spacing(1.5),
  },
  serveModeSeparator: {
    width: 0,
  },
  serveModeCard: {
    width: 188,
    backgroundColor: `${colors.bg}90`,
    borderRadius: radii.md,
    padding: spacing(1.5),
    borderWidth: 1,
    borderColor: colors.line,
    gap: spacing(0.5),
  },
  serveModeIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: `${colors.gold}12`,
    marginBottom: spacing(0.5),
  },
  serveModeLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.text,
  },
  serveModeDescription: {
    fontSize: 13,
    color: colors.subtext,
    lineHeight: 18,
  },
  serveFootnote: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(0.75),
  },
  serveFootnoteText: {
    flex: 1,
    fontSize: 12,
    color: colors.subtext,
    lineHeight: 17,
  },
  serveUpgradeText: {
    fontSize: 12,
    color: colors.accent,
    lineHeight: 17,
  },
  section: {
    marginBottom: spacing(3),
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: colors.text,
    marginBottom: spacing(1.5),
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(1.5),
    marginBottom: spacing(1.5),
  },
  categoryDefaultBadge: {
    fontSize: 11,
    fontWeight: '500',
    color: colors.subtext,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing(1),
    paddingVertical: 2,
    borderRadius: radii.sm,
    textTransform: 'capitalize',
    opacity: 0.7,
  },
  flavorGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing(1.5),
    marginTop: spacing(0.5),
  },
  flavorIconCell: {
    width: '30%',
    alignItems: 'center',
    gap: spacing(0.75),
  },
  flavorIconCircle: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: colors.gold,
    alignItems: 'center',
    justifyContent: 'center',
  },
  flavorIconLabel: {
    fontSize: 11,
    fontWeight: '500',
    color: colors.subtext,
    textAlign: 'center',
    lineHeight: 14,
  },
  tastingNotes: {
    fontSize: 15,
    color: colors.subtext,
    lineHeight: 22,
  },
  cellarCard: {
    borderRadius: radii.lg,
    padding: spacing(2),
    marginBottom: spacing(3),
    borderWidth: 1,
    gap: spacing(1.5),
  },
  cellarCardActive: {
    backgroundColor: `${colors.gold}10`,
    borderColor: `${colors.gold}36`,
  },
  cellarCardLocked: {
    backgroundColor: colors.card,
    borderColor: colors.line,
  },
  cellarHeader: {
    flexDirection: 'row',
    gap: spacing(1.5),
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  cellarHeaderActions: {
    alignItems: 'flex-end',
    gap: spacing(0.75),
  },
  cellarHeaderCopy: {
    flex: 1,
    gap: spacing(0.5),
  },
  cellarEyebrow: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.accent,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  cellarTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.text,
  },
  cellarSubtitle: {
    fontSize: 13,
    lineHeight: 18,
    color: colors.subtext,
  },
  cellarBadge: {
    paddingHorizontal: spacing(1.25),
    paddingVertical: spacing(0.75),
    borderRadius: radii.full,
    backgroundColor: `${colors.bg}99`,
    borderWidth: 1,
    borderColor: `${colors.gold}28`,
  },
  cellarBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.gold,
  },
  cellarCollapseButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(0.4),
    paddingHorizontal: spacing(1),
    paddingVertical: spacing(0.55),
    borderRadius: radii.full,
    borderWidth: 1,
    borderColor: `${colors.accent}35`,
    backgroundColor: `${colors.accent}10`,
  },
  cellarCollapseButtonText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.accent,
  },
  cellarSummaryRow: {
    flexDirection: 'row',
    gap: spacing(0.9),
  },
  cellarSummaryPill: {
    flex: 1,
    backgroundColor: `${colors.bg}88`,
    borderRadius: radii.full,
    borderWidth: 1,
    borderColor: colors.line,
    paddingHorizontal: spacing(1.2),
    paddingVertical: spacing(1),
    gap: spacing(0.3),
  },
  cellarSummaryLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.subtext,
    textTransform: 'uppercase',
    letterSpacing: 0.7,
  },
  cellarSummaryValue: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.text,
  },
  cellarMetricsRow: {
    flexDirection: 'row',
    gap: spacing(1.25),
  },
  cellarMetric: {
    flex: 1,
    backgroundColor: `${colors.bg}90`,
    borderRadius: radii.md,
    padding: spacing(1.5),
    borderWidth: 1,
    borderColor: colors.line,
    gap: spacing(0.5),
  },
  cellarMetricLabel: {
    fontSize: 10,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    fontWeight: '700',
    color: colors.subtext,
  },
  cellarMetricValue: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.text,
  },
  cellarWindowCard: {
    backgroundColor: `${colors.bg}85`,
    borderRadius: radii.md,
    padding: spacing(1.5),
    borderWidth: 1,
    borderColor: colors.line,
    gap: spacing(0.5),
  },
  cellarWindowTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.accent,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  cellarWindowValue: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
  },
  cellarWindowNote: {
    fontSize: 13,
    lineHeight: 18,
    color: colors.subtext,
  },
  cellarNotesCard: {
    backgroundColor: `${colors.bg}70`,
    borderRadius: radii.md,
    padding: spacing(1.5),
    borderWidth: 1,
    borderColor: colors.line,
    gap: spacing(0.5),
  },
  cellarNotesTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.text,
  },
  cellarNotesBody: {
    fontSize: 13,
    lineHeight: 18,
    color: colors.subtext,
  },
  cellarButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing(1),
    backgroundColor: colors.accent,
    borderRadius: radii.lg,
    paddingVertical: spacing(1.75),
  },
  cellarButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.white,
  },
  cellarSecondaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing(0.75),
    borderRadius: radii.lg,
    paddingVertical: spacing(1.5),
    borderWidth: 1,
    borderColor: `${colors.accent}40`,
    backgroundColor: `${colors.accent}10`,
  },
  cellarSecondaryButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.accent,
  },
  cellarUpgradeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing(0.75),
    borderRadius: radii.lg,
    paddingVertical: spacing(1.5),
    borderWidth: 1,
    borderColor: `${colors.accent}50`,
    backgroundColor: `${colors.accent}10`,
  },
  cellarUpgradeButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.accent,
  },
  cellarEmptyState: {
    gap: spacing(0.75),
  },
  cellarEmptyTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.text,
  },
  cellarEmptyBody: {
    fontSize: 13,
    lineHeight: 18,
    color: colors.subtext,
  },
  cellarModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    padding: spacing(3),
  },
  cellarModalCard: {
    backgroundColor: colors.card,
    borderRadius: radii.lg,
    padding: spacing(3),
    borderWidth: 1,
    borderColor: colors.line,
  },
  cellarModalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.text,
    marginBottom: spacing(0.5),
  },
  cellarModalSubtitle: {
    fontSize: 13,
    lineHeight: 18,
    color: colors.subtext,
    marginBottom: spacing(2),
  },
  cellarInputLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.accent,
    marginBottom: spacing(0.75),
    marginTop: spacing(1.25),
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  cellarInput: {
    backgroundColor: colors.bg,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.line,
    paddingHorizontal: spacing(1.5),
    paddingVertical: spacing(1.25),
    color: colors.text,
    fontSize: 15,
  },
  cellarWindowInputs: {
    flexDirection: 'row',
    gap: spacing(1),
  },
  cellarWindowInput: {
    flex: 1,
  },
  quantityRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing(1),
  },
  quantityChip: {
    paddingHorizontal: spacing(1.25),
    paddingVertical: spacing(0.9),
    borderRadius: radii.full,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.bg,
  },
  quantityChipActive: {
    borderColor: `${colors.accent}50`,
    backgroundColor: `${colors.accent}15`,
  },
  quantityChipText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.subtext,
  },
  quantityChipTextActive: {
    color: colors.accent,
  },
  cellarNotesInput: {
    minHeight: 96,
    textAlignVertical: 'top',
  },
  cellarModalActions: {
    flexDirection: 'row',
    gap: spacing(1.5),
    marginTop: spacing(2.5),
  },
  cellarModalSecondary: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radii.lg,
    paddingVertical: spacing(1.5),
    borderWidth: 1,
    borderColor: colors.line,
  },
  cellarModalSecondaryText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
  },
  cellarModalPrimary: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radii.lg,
    paddingVertical: spacing(1.5),
    backgroundColor: colors.accent,
  },
  cellarModalPrimaryText: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.white,
  },
  cocktailsHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing(1),
    marginBottom: spacing(2),
  },
  cocktailsHeaderCopy: {
    flex: 1,
  },
  cocktailsTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: colors.text,
  },
  cocktailsSubtitle: {
    marginTop: spacing(0.5),
    fontSize: 12,
    color: colors.subtext,
  },
  cocktailsRail: {
    paddingLeft: spacing(0.25),
    paddingRight: spacing(2),
  },
  cocktailRailSeparator: {
    width: spacing(2),
  },
  discoveryRecipeCard: {
    width: 240,
  },
  lockedRecipeTeaser: {
    width: 200,
    marginLeft: spacing(2),
    borderRadius: 20,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(214,138,56,0.22)',
    backgroundColor: 'rgba(20,13,9,0.92)',
  },
  lockedRecipeTeaserContent: {
    flex: 1,
    padding: spacing(2),
    justifyContent: 'center',
    minHeight: 220,
  },
  lockedRecipeLockBadge: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(214,138,56,0.14)',
    borderWidth: 1,
    borderColor: 'rgba(214,138,56,0.3)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing(1.25),
  },
  lockedRecipeTeaserName: {
    fontSize: 18,
    fontWeight: '700',
    color: 'rgba(246,236,228,0.5)',
    lineHeight: 22,
    marginBottom: spacing(0.5),
  },
  lockedRecipeTeaserSub: {
    fontSize: 12,
    color: 'rgba(160,140,128,0.6)',
    marginBottom: spacing(1.5),
  },
  lockedRecipeTeaserDivider: {
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.08)',
    marginBottom: spacing(1.25),
  },
  lockedRecipeTeaserCta: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.accent,
  },
  lockedRecipeCardInRail: {
    width: 240,
    height: 320,
    marginLeft: spacing(2),
  },
  seeMoreToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing(0.5),
    paddingVertical: spacing(2),
  },
  seeMoreToggleText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.accent,
  },
  actions: {
    gap: spacing(2),
    marginTop: spacing(2),
  },
  primaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing(1),
    backgroundColor: colors.accent,
    borderRadius: radii.lg,
    padding: spacing(2),
  },
  primaryButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.white,
  },
  tryAnotherButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing(1),
    backgroundColor: colors.card,
    borderRadius: radii.lg,
    padding: spacing(2),
    borderWidth: 2,
    borderColor: colors.accent,
  },
  tryAnotherButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
  },
  secondaryActions: {
    flexDirection: 'row',
    gap: spacing(2),
  },
  secondaryButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing(1),
    backgroundColor: colors.card,
    borderRadius: radii.lg,
    paddingVertical: spacing(2.5),
    paddingHorizontal: spacing(2),
    borderWidth: 1,
    borderColor: colors.line,
  },
  secondaryButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
  },
  secondaryButtonActive: {
    backgroundColor: `${colors.gold}14`,
    borderColor: colors.gold,
  },
  invConfirmBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.72)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing(4),
  },
  invConfirmCard: {
    width: '100%',
    backgroundColor: '#1A1108',
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: 'rgba(214,138,56,0.25)',
    padding: spacing(4),
    alignItems: 'center',
  },
  invConfirmIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: 'rgba(214,138,56,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(214,138,56,0.3)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing(2),
  },
  invConfirmTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.text,
    marginBottom: spacing(0.5),
  },
  invConfirmBottleName: {
    fontSize: 14,
    color: colors.subtext,
    textAlign: 'center',
    marginBottom: spacing(1.5),
  },
  invConfirmXP: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(0.5),
    backgroundColor: 'rgba(214,138,56,0.1)',
    borderRadius: radii.sm,
    paddingHorizontal: spacing(1.5),
    paddingVertical: spacing(0.5),
    marginBottom: spacing(3),
  },
  invConfirmXPText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.gold,
  },
  invConfirmActions: {
    flexDirection: 'row',
    gap: spacing(2),
    width: '100%',
    marginBottom: spacing(2),
  },
  invConfirmSecondary: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing(1.75),
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.card,
  },
  invConfirmSecondaryText: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.text,
  },
  invConfirmPrimary: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing(1.75),
    borderRadius: radii.lg,
    backgroundColor: colors.accent,
  },
  invConfirmPrimaryText: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.white,
  },
  invConfirmDismiss: {
    paddingVertical: spacing(1),
  },
  invConfirmDismissText: {
    fontSize: 14,
    color: colors.subtext,
  },
  feedbackStrip: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: `${colors.accent}12`,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: `${colors.accent}30`,
    paddingHorizontal: spacing(2),
    paddingVertical: spacing(1.5),
    marginBottom: spacing(3),
    gap: spacing(2),
  },
  feedbackQuestion: {
    flex: 1,
    fontSize: 13,
    fontWeight: '500',
    color: colors.subtext,
  },
  feedbackStripProminent: {
    backgroundColor: 'rgba(255,152,0,0.1)',
    borderColor: 'rgba(255,152,0,0.35)',
  },
  feedbackStripCorrection: {
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: spacing(1),
  },
  correctionLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.text,
    marginBottom: spacing(0.5),
  },
  correctionOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(1.5),
    paddingVertical: spacing(1.25),
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
  },
  correctionOptionIcon: {
    width: 36,
    height: 36,
    borderRadius: radii.md,
    backgroundColor: colors.bg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  correctionOptionBody: {
    flex: 1,
    gap: 2,
  },
  correctionOptionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
  },
  correctionOptionSub: {
    fontSize: 11,
    color: colors.subtext,
  },
  correctionInput: {
    backgroundColor: colors.bg,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: colors.line,
    paddingHorizontal: spacing(1.5),
    paddingVertical: spacing(1),
    fontSize: 14,
    color: colors.text,
  },
  correctionActions: {
    flexDirection: 'row',
    gap: spacing(1),
    marginTop: spacing(0.5),
  },
  correctionSubmit: {
    flex: 1,
    backgroundColor: colors.gold,
    borderRadius: radii.sm,
    paddingVertical: spacing(1),
    alignItems: 'center',
    justifyContent: 'center',
  },
  correctionSubmitText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1A120D',
  },
  correctionCancel: {
    paddingHorizontal: spacing(2),
    paddingVertical: spacing(1),
    alignItems: 'center',
    justifyContent: 'center',
  },
  correctionCancelText: {
    fontSize: 13,
    color: colors.subtext,
  },
  feedbackQuestionProminent: {
    color: colors.text,
    fontWeight: '600',
  },
  feedbackConfirmedText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.gold,
    marginLeft: spacing(1),
  },
  feedbackButtons: {
    flexDirection: 'row',
    gap: spacing(1),
  },
  feedbackYes: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(0.5),
    backgroundColor: `${colors.accent}20`,
    borderRadius: radii.sm,
    paddingHorizontal: spacing(1.5),
    paddingVertical: spacing(0.75),
    borderWidth: 1,
    borderColor: `${colors.accent}40`,
  },
  feedbackYesText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.gold,
  },
  feedbackNo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(0.5),
    backgroundColor: colors.card,
    borderRadius: radii.sm,
    paddingHorizontal: spacing(1.5),
    paddingVertical: spacing(0.75),
    borderWidth: 1,
    borderColor: colors.line,
  },
  feedbackNoText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.subtext,
  },
  // ── Flavour strip ──────────────────────────────────────────────────────────
  flavourStrip: {
    marginBottom: spacing(2),
  },
  flavourStripContent: {
    paddingHorizontal: spacing(2),
    gap: spacing(1),
    flexDirection: 'row',
  },
  flavourPill: {
    backgroundColor: `${colors.accent}18`,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: `${colors.accent}35`,
    paddingHorizontal: spacing(1.75),
    paddingVertical: spacing(0.6),
  },
  flavourPillText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.gold,
  },
  // ── What else do I need ────────────────────────────────────────────────────
  missingSection: {
    backgroundColor: colors.card,
    borderRadius: radii.lg,
    padding: spacing(2),
    marginBottom: spacing(2),
    gap: spacing(1.5),
  },
  missingSectionTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.text,
    marginBottom: spacing(0.5),
  },
  missingRow: {
    gap: spacing(0.75),
  },
  missingRecipeName: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.subtext,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  missingIngredients: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing(0.75),
  },
  missingPill: {
    backgroundColor: colors.bg,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: colors.line,
    paddingHorizontal: spacing(1.25),
    paddingVertical: spacing(0.4),
  },
  missingPillText: {
    fontSize: 12,
    color: colors.text,
  },
  missingMore: {
    fontSize: 12,
    color: colors.subtext,
    alignSelf: 'center',
  },
  // ── Sticky shelf action bar ────────────────────────────────────────────────
  stickyShelfBar: {
    borderTopWidth: 1,
    borderTopColor: colors.line,
    backgroundColor: colors.bg,
    paddingHorizontal: spacing(3),
    paddingTop: spacing(1.5),
  },
  stickyShelfButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing(1),
    paddingVertical: spacing(1.75),
    borderRadius: radii.lg,
    backgroundColor: colors.gold,
  },
  stickyShelfButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.goldText,
  },
  stickyShelfConfirmed: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing(0.75),
    paddingVertical: spacing(1.75),
  },
  stickyShelfConfirmedText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.gold,
    flex: 1,
  },
  // ── Legacy shelf action (kept for shelfActionViewLink ref) ─────────────────
  shelfAction: {
    alignItems: 'center',
    paddingTop: spacing(2),
    paddingHorizontal: spacing(4),
  },
  shelfActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(1),
    paddingHorizontal: spacing(6),
    paddingVertical: spacing(2),
    borderRadius: radii.lg,
    borderWidth: 1.5,
    borderColor: colors.line,
    backgroundColor: colors.card,
  },
  shelfActionButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.text,
  },
  shelfActionConfirmed: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(0.75),
  },
  shelfActionConfirmedText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.gold,
    flex: 1,
  },
  shelfActionViewLink: {
    fontSize: 12,
    color: colors.accent,
  },
  // ── Wrong result link ──────────────────────────────────────────────────────
  wrongResultLink: {
    alignItems: 'center',
    paddingVertical: spacing(1.5),
  },
  wrongResultLinkText: {
    fontSize: 12,
    color: colors.subtext,
    textDecorationLine: 'underline',
  },
  // ── Wishlist ──────────────────────────────────────────────────────────────
  wishlistRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing(1),
    paddingVertical: spacing(1),
  },
  wishlistLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(0.75),
  },
  wishlistLinkText: {
    fontSize: 12,
    color: colors.subtext,
  },
  wishlistSavedText: {
    fontSize: 12,
    color: colors.accent,
  },
  wishlistRemoveText: {
    fontSize: 12,
    color: colors.subtext,
    textDecorationLine: 'underline',
  },
  // ── Price prompt modal ────────────────────────────────────────────────────
  pricePromptOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing(3),
  },
  pricePromptCard: {
    backgroundColor: colors.card,
    borderRadius: radii.xl,
    padding: spacing(3),
    width: '100%',
    gap: spacing(1.5),
    borderWidth: 1,
    borderColor: colors.line,
  },
  pricePromptTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: colors.text,
  },
  pricePromptSubtitle: {
    fontSize: 13,
    color: colors.subtext,
    lineHeight: 18,
  },
  pricePromptInput: {
    backgroundColor: colors.bg,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: radii.md,
    paddingHorizontal: spacing(2),
    paddingVertical: spacing(1.5),
    fontSize: 14,
    color: colors.text,
  },
  pricePromptActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: spacing(2),
    marginTop: spacing(0.5),
  },
  pricePromptSkip: {
    paddingVertical: spacing(1),
    paddingHorizontal: spacing(1.5),
  },
  pricePromptSkipText: {
    fontSize: 14,
    color: colors.subtext,
  },
  pricePromptSave: {
    backgroundColor: colors.accent,
    borderRadius: radii.md,
    paddingVertical: spacing(1),
    paddingHorizontal: spacing(2.5),
  },
  pricePromptSaveText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.bg,
  },
  // ── Horizontal info cards (flavor/tasting + serve/about) ──────────────────
  infoCardsScroll: {
    marginBottom: spacing(3),
  },
  infoCardsContent: {
    gap: 0,
  },
  infoCard: {
    width: Dimensions.get('window').width - spacing(3) * 2,
    marginBottom: 0,
  },
  infoCardHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(1.5),
    marginBottom: spacing(1.5),
  },
  infoCardTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: colors.text,
  },
  infoCardDots: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: spacing(1),
    marginBottom: spacing(3),
    marginTop: spacing(1),
  },
  infoCardsDotsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: spacing(1),
    marginBottom: spacing(1.5),
  },
  infoCardDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.line,
  },
  infoCardDotActive: {
    backgroundColor: colors.gold,
    width: 16,
  },
  // ── Currency picker ────────────────────────────────────────────────────────
  regionBadgeTappable: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: `${colors.accent}20`,
    paddingHorizontal: spacing(1),
    paddingVertical: spacing(0.5),
    borderRadius: radii.sm,
  },
  regionBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.accent,
  },
  currencyModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  currencyModalSheet: {
    backgroundColor: colors.card,
    borderTopLeftRadius: radii.xl,
    borderTopRightRadius: radii.xl,
    padding: spacing(3),
    paddingBottom: spacing(5),
    gap: spacing(0.5),
  },
  currencyModalHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.line,
    alignSelf: 'center',
    marginBottom: spacing(2),
  },
  currencyModalTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: colors.text,
    marginBottom: spacing(1.5),
  },
  currencyOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(1.5),
    paddingVertical: spacing(1.5),
    paddingHorizontal: spacing(1),
    borderRadius: radii.md,
  },
  currencyOptionActive: {
    backgroundColor: `${colors.gold}15`,
  },
  currencyOptionFlag: {
    fontSize: 24,
  },
  currencyOptionLabels: {
    flex: 1,
    gap: 2,
  },
  currencyOptionCode: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.text,
  },
  currencyOptionCodeActive: {
    color: colors.gold,
  },
  currencyOptionName: {
    fontSize: 12,
    color: colors.subtext,
  },
  // ── Taste signal + thumbs ─────────────────────────────────────────────────
  tasteSignalLine: {
    fontSize: 13,
    color: colors.subtext,
    marginHorizontal: spacing(4),
    marginTop: spacing(0.5),
    marginBottom: spacing(1),
    lineHeight: 18,
  },
  thumbsRow: {
    flexDirection: 'row',
    gap: spacing(2),
    paddingHorizontal: spacing(4),
    paddingBottom: spacing(1),
  },
  thumbsButton: {
    padding: spacing(0.5),
  },
  correctionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing(1),
    paddingHorizontal: spacing(4),
    paddingBottom: spacing(1.5),
  },
  correctionPill: {
    paddingHorizontal: spacing(2),
    paddingVertical: spacing(0.75),
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.card,
  },
  correctionPillText: {
    fontSize: 12,
    color: colors.subtext,
  },
});
