/**
 * Cocktail Images
 * Local image assets for cocktails
 */

export const COCKTAIL_IMAGES: Record<string, any> = {
  // Base cocktails (ensure consistency with variations)
  'old-fashioned': require('./cocktails/Old Fashioned.png'),
  'martini': require('./cocktails/Dry Martini.png'),

  // Existing images (from original export)
  'espresso-martini': require('./cocktails/espresso-martini.png'),
  'margarita': require('./cocktails/margarita.png'),
  'mimosa': require('./cocktails/mimosa.png'),
  'mojito': require('./cocktails/mojito.png'),
  'negroni': require('./cocktails/negroni.png'),
  'pina-colada': require('./cocktails/pina-colada.png'),
  'aperol-spritz': require('./cocktails/aperol-spritz.png'),
  'dark-stormy': require('./cocktails/dark-stormy.png'),
  'boulevardier': require('./cocktails/boulevardier.png'),
  'black-russian': require('./cocktails/Black Russian - Classic.png'),
  'brandy-alexander': require('./cocktails/Brandy Alexander.png'),
  'brandy-crusta': require('./cocktails/Brandy Crusta.png'),
  'brandy-milk-punch': require('./cocktails/Brandy Milk Punch.png'),
  'brooklyn': require('./cocktails/Brooklyn.png'),
  'caipirinha': require('./cocktails/Caipirinha.png'),
  'corpse-reviver-1': require('./cocktails/Corpse Reviver #1.png'),
  'dry-martini': require('./cocktails/Dry Martini.png'),
  'fog-cutter': require('./cocktails/Fog Cutter.png'),
  'french-75': require('./cocktails/French 75 - Spiral Garnish.png'),
  'gimlet': require('./cocktails/Gimlet.png'),
  'gin-rickey': require('./cocktails/Gin Rickey.png'),
  'golden-cadillac': require('./cocktails/Golden Cadillac.png'),
  'grasshopper': require('./cocktails/Grasshopper.png'),
  'hanky-panky': require('./cocktails/Hanky Highball.png'),
  'hemingway-daiquiri': require('./cocktails/Hemingway Daiquiri - Classic.png'),
  'highball': require('./cocktails/Highball.png'),
  'hugo': require('./cocktails/Hugo.png'),
  'hurricane': require('./cocktails/Hurricane.png'),
  'john-collins': require('./cocktails/John Collins.png'),
  'jungle-bird': require('./cocktails/Jungle Bird.png'),
  'kentucky-mule': require('./cocktails/Kentucky Mule - Mint-1.png'),
  'martinez': require('./cocktails/Martinez.png'),
  'missionary-downfall': require('./cocktails/Missionarys-Downfall.png'),
  'mudslide': require('./cocktails/Mudslide.png'),
  'navy-grog': require('./cocktails/Navy Grog.png'),
  'negroni-sbagliato': require('./cocktails/Negroni Sbagliato.png'),
  'old-fashioned-classic': require('./cocktails/Old Fashioned.png'),
  'painkiller': require('./cocktails/Painkiller.png'),
  'paper-plane': require('./cocktails/Paper Plane-1.png'),
  'pearl-diver': require('./cocktails/Pearl Diver.png'),
  'pink-squirrel': require('./cocktails/Pink Squirrel-1.png'),
  'ramos-gin-fizz': require('./cocktails/Ramos Gin Fizz.png'),

  // Additional Classic Cocktails
  'alexander': require('./cocktails/Alexander - Classic.png'),
  'amaretto-sour': require('./cocktails/Amaretto Sour - Classic.png'),
  'americano': require('./cocktails/Americano - Classic.png'),
  'aviation': require('./cocktails/Aviation - Classic.png'),
  'bee-knees': require("./cocktails/Bee's Knees - Classic.png"),
  'bellini': require('./cocktails/Bellini - Classic.png'),
  'bloody-mary': require('./cocktails/Bloody Mary - Classic.png'),
  'blue-hawaiian': require('./cocktails/Blue Hawaiian.png'),
  'bramble': require('./cocktails/Bramble.png'),
  'casino': require('./cocktails/Casino.png'),
  'champagne-cocktail': require('./cocktails/Champagne Cocktail.png'),
  'daiquiri': require('./cocktails/Classic Daiquiri.png'),
  'margarita-classic': require('./cocktails/Classic Margarita.png'),
  'clover-club': require('./cocktails/Clover Club.png'),
  'corpse-reviver-2': require('./cocktails/Corpse Reviver #2.png'),
  'cosmopolitan': require('./cocktails/Cosmopolitan.png'),
  'demerara-syrup': require('./cocktails/Demerara Syrup.png'),
  'derby': require('./cocktails/Derby.png'),

  // Tier 1: Classic Must-Haves
  'manhattan': require('./cocktails/Manhattan.png'),
  'moscow-mule': require('./cocktails/Moscow Mule.png'),
  'whiskey-sour': require('./cocktails/Whiskey Sour.png'),
  'gin-tonic': require('./cocktails/Gin & Tonic.png'),
  'last-word': require('./cocktails/Last Word.png'),
  'sazerac': require('./cocktails/Sazerac.png'),
  'sidecar': require('./cocktails/Sidecar.png'),
  'white-russian': require('./cocktails/White Russian.png'),
  'tequila-sunrise': require('./cocktails/Tequila Sunrise.png'),
  'long-island': require('./cocktails/Long Island Iced Tea.png'),
  'irish-coffee': require('./cocktails/Irish Coffee.png'),
  'tom-collins': require('./cocktails/Tom Collins.png'),
  'pisco-sour': require('./cocktails/Pisco Sour.png'),

  // Tier 2: Popular Modern Classics
  'lemon-drop': require('./cocktails/Lemon Drop.png'),
  'paloma': require('./cocktails/Paloma.png'),
  'penicillin': require('./cocktails/Penicillin.png'),
  'gold-rush': require('./cocktails/Gold Rush.png'),
  'naked-and-famous': require('./cocktails/Naked and Famous .png'),
  'vesper': require('./cocktails/Vesper.png'),
  'southside': require('./cocktails/Southside.png'),
  'mezcal-mule': require('./cocktails/Mezcal Mule.png'),

  // Tier 3: Variations & Specialty
  'oaxaca-old-fashioned': require('./cocktails/Oaxaca Old Fashioned.png'),
  'new-york-sour': require('./cocktails/New York Sour.png'),
  'margarita-frozen': require('./cocktails/Frozen Margarita.png'),
  'tommy-margarita': require("./cocktails/Tommy’s Margarita.png"),
  'french-martini': require('./cocktails/French Martini.png'),
  'vodka-martini': require('./cocktails/Vodka Martini.png'),
  'gibson': require('./cocktails/Gibson.png'),
  'spritz-veneziano': require('./cocktails/Spritz Veneziano.png'),
  'vieux-carre': require('./cocktails/Vieux Carré.png'),
  'rusty-nail': require('./cocktails/Rusty Nail.png'),
  'godfather': require('./cocktails/Godfather.png'),
  'godmother': require('./cocktails/Godmother.png'),
  'stinger': require('./cocktails/Stinger.png'),
  'rob-roy': require('./cocktails/Rob Roy.png'),
  'french-connection': require('./cocktails/French Connection.png'),
  'hot-toddy': require('./cocktails/Hot Toddy.png'),
  'whiskey-smash': require('./cocktails/Whiskey Smash.png'),
  'gin-fizz': require('./cocktails/Gin Fizz.png'),
  'planters-punch': require("./cocktails/Planter's Punch.png"),
  'rum-punch': require("./cocktails/Planter's Punch.png"),
  'screwdriver': require('./cocktails/Screwdriver.png'),
  'sea-breeze': require('./cocktails/Sea Breeze.png'),
  'sex-on-the-beach': require('./cocktails/Sex on the Beach.png'),
  'vodka-soda': require('./cocktails/Vodka Soda.png'),
  'ranch-water': require('./cocktails/Ranch Water.png'),
  'revolver': require('./cocktails/Revolver.png'),
  'white-lady': require('./cocktails/White Lady.png'),

  // Tier 4: Syrups & Less Common
  'grenadine': require('./cocktails/Grenadine.png'),
  'honey-syrup': require('./cocktails/Honey Syrup.png'),
  'fernandito': require('./cocktails/Fernandito.png'),
  'hemingway-special': require('./cocktails/Hemingway Special.png'),
  'horses-neck': require("./cocktails/Horse's Neck.png"),
  'kir': require('./cocktails/Kir.png'),
  'kir-royale': require('./cocktails/Kir Royale.png'),
  'lynchburg-lemonade': require('./cocktails/Lynchburg Lemonade.png'),
  'mary-pickford': require('./cocktails/Mary Pickford.png'),
  'russian-spring-punch': require('./cocktails/Russian Spring Punch.png'),
  'saturn': require('./cocktails/Saturn.png'),
  'south-side-fizz': require('./cocktails/Southside Fizz.png'),
  'test-pilot': require('./cocktails/Test Pilot.png'),
  'three-dots-dash': require('./cocktails/Three Dots and a Dash.png'),
  'trader-vics-grog': require('./cocktails/Trader-Vics-Grog-.png'),
  'trinidad-sour': require('./cocktails/Trinidad Sour.png'),
  'ward-8': require('./cocktails/Ward 8.png'),
  'zombie': require('./cocktails/Zombie Variation.png'),

  // NEW: Syrups (Nov 19, 2025)
  'simple-syrup': require('./cocktails/Simple Syrup.png'),
  'demerara-syrup': require('./cocktails/Demerara Syrup.png'),
  'cinnamon-syrup': require('./cocktails/Cinnamon Syrup.png'),
  'ginger-syrup': require('./cocktails/Ginger Syrup.png'),
  'vanilla-syrup': require('./cocktails/Vanilla Syrup.png'),
  'mint-syrup': require('./cocktails/Mint Syrup.png'),
  'lavender-syrup': require('./cocktails/Lavender Syrup.png'),
  'rosemary-syrup': require('./cocktails/Rosemary Syrup.png'),
  'cardamom-syrup': require('./cocktails/Cardamom Syrup.png'),
  'chili-syrup': require('./cocktails/Chili Syrup.png'),
  'blackberry-syrup': require('./cocktails/Blackberry Syrup.png'),
  'strawberry-syrup': require('./cocktails/Strawberry Syrup.png'),
  'passionfruit-syrup': require('./cocktails/Passionfruit Syrup.png'),
  'pineapple-syrup': require('./cocktails/Pineapple Syrup.png'),
  'orgeat': require('./cocktails/Orgeat.png'),
  'grenadine-syrup': require('./cocktails/Grenadine.png'),

  // NEW: Cocktail Variations (Nov 19, 2025)
  'mai-tai': require('./cocktails/Mai Tai.png'),
  'mai-tai-variation': require('./cocktails/Mai Tai.png'),
  'mint-julep-variation': require('./cocktails/Mint Julep.png'),
  'mint-julep': require('./cocktails/Mint Julep.png'),
  'pornstar-martini-variation': require('./cocktails/Pornstar Martini.png'),
  'pornstar-martini': require('./cocktails/Pornstar Martini.png'),
  'saturn-variation': require('./cocktails/Saturn.png'),
  'singapore-sling-variation': require('./cocktails/Singapore Sling.png'),
  'singapore-sling': require('./cocktails/Singapore Sling.png'),
  'southside-fizz-variation': require('./cocktails/Southside Fizz.png'),
  'southside-fizz': require('./cocktails/Southside Fizz.png'),
  'stinger-variation': require('./cocktails/Stinger.png'),
  'old-cuban': require('./cocktails/Old Cuban.png'),
  'porto-flip': require('./cocktails/Porto Flip.png'),
  'zombie-variation': require('./cocktails/Zombie Variation.png'),
};

/**
 * Get cocktail image by recipe ID
 * Returns local image if available, otherwise returns provided URL
 */
export function getCocktailImage(recipeId: string, fallbackUrl?: string): any {
  return COCKTAIL_IMAGES[recipeId] || fallbackUrl;
}
