export type UnlockTier = 'FREE' | 'PLUS' | 'PRO';
export type UnlockFormat = 'standard_recipe' | 'premium_recipe_card' | 'mixology_recipe_card' | 'mini_deck' | 'utility_card';
export type UnlockKind = 'recipe' | 'recipe_card' | 'deck' | 'utility';
export type UnlockStatus = 'planned' | 'ready';

export interface CurriculumUnlock {
  id: string;
  moduleId: string;
  lessonId: string;
  tier: UnlockTier;
  format: UnlockFormat;
  kind: UnlockKind;
  assetName: string;
  description: string;
  status: UnlockStatus;
  rewardPhase: 'midpoint' | 'late_module' | 'checkpoint' | 'module_completion';
  watermark: {
    enabled: boolean;
    label: string;
    placement: 'footer' | 'background';
    tierBadge?: UnlockTier;
  };
  recipeIds?: string[];
  assetSlug?: string;
  notes?: string;
}

export const CURRICULUM_UNLOCKS: CurriculumUnlock[] = [
  {
    id: 'unlock-basics-house-daiquiri',
    moduleId: 'ch1-bartending-basics',
    lessonId: 'ch1-bartending-basics.lesson03',
    tier: 'FREE',
    format: 'standard_recipe',
    kind: 'recipe',
    assetName: 'House Daiquiri Spec',
    description: 'A clean, foundational spec that rewards early confidence and teaches balance through simplicity.',
    status: 'ready',
    rewardPhase: 'midpoint',
    watermark: { enabled: false, label: 'KOOPE', placement: 'footer' },
    recipeIds: ['house-daiquiri-spec'],
    assetSlug: 'house-daiquiri-spec',
  },
  {
    id: 'unlock-basics-glassware-cheat-sheet',
    moduleId: 'ch1-bartending-basics',
    lessonId: 'ch1-bartending-basics.lesson03',
    tier: 'FREE',
    format: 'mini_deck',
    kind: 'deck',
    assetName: 'Glassware Cheat Sheet',
    description: 'A quick field guide for matching glass shape to structure, dilution, and presentation.',
    status: 'ready',
    rewardPhase: 'midpoint',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer' },
    assetSlug: 'glassware-cheat-sheet',
  },
  {
    id: 'unlock-basics-shopping-cart-guide',
    moduleId: 'ch1-bartending-basics',
    lessonId: 'ch1-bartending-basics.lesson02',
    tier: 'FREE',
    format: 'mini_deck',
    kind: 'deck',
    assetName: 'Shopping Cart Smart Buy Guide',
    description: 'A prep buying guide for prioritizing bottles, citrus, and basics without overspending or overbuying.',
    status: 'ready',
    rewardPhase: 'midpoint',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer' },
    assetSlug: 'shopping-cart-smart-buy-guide',
  },
  {
    id: 'unlock-basics-bar-setup-guide',
    moduleId: 'ch1-bartending-basics',
    lessonId: 'ch1-bartending-basics.lesson07',
    tier: 'FREE',
    format: 'utility_card',
    kind: 'utility',
    assetName: 'Bar Setup Quick Guide',
    description: 'A practical station-prep card users can reference before hosting or practice sessions.',
    status: 'planned',
    rewardPhase: 'late_module',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer' },
    assetSlug: 'bar-setup-quick-guide',
  },
  {
    id: 'unlock-basics-fresh-citrus-storage',
    moduleId: 'ch1-bartending-basics',
    lessonId: 'ch1-bartending-basics.lesson08',
    tier: 'FREE',
    format: 'mini_deck',
    kind: 'deck',
    assetName: 'Fresh Citrus Storage Hacks',
    description: 'A prep deck for keeping citrus brighter, longer, and more service-ready at home.',
    status: 'ready',
    rewardPhase: 'late_module',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer' },
    assetSlug: 'fresh-citrus-storage-hacks',
  },
  {
    id: 'unlock-basics-herb-garnish-preservation',
    moduleId: 'ch1-bartending-basics',
    lessonId: 'ch1-bartending-basics.lesson07',
    tier: 'FREE',
    format: 'mini_deck',
    kind: 'deck',
    assetName: 'Herb & Garnish Preservation Hacks',
    description: 'A prep deck for keeping herbs and garnishes cleaner, brighter, and more service-ready for longer.',
    status: 'ready',
    rewardPhase: 'late_module',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer' },
    assetSlug: 'herb-garnish-preservation-hacks',
  },
  {
    id: 'unlock-basics-checkpoint-card',
    moduleId: 'ch1-bartending-basics',
    lessonId: 'ch1-bartending-basics.lesson10',
    tier: 'FREE',
    format: 'premium_recipe_card',
    kind: 'recipe_card',
    assetName: "Bartender's Lemon Sour",
    description: 'Checkpoint card reward for completing the fundamentals path with a practical, polished house-style serve.',
    status: 'planned',
    rewardPhase: 'checkpoint',
    watermark: { enabled: true, label: 'KOOPE', placement: 'background' },
    assetSlug: 'bartenders-lemon-sour-card',
  },
  {
    id: 'unlock-techniques-house-martini',
    moduleId: 'ch3-techniques-prep',
    lessonId: 'ch3-techniques-prep.lesson03',
    tier: 'FREE',
    format: 'standard_recipe',
    kind: 'recipe',
    assetName: 'Stirred House Martini',
    description: 'A technique-led unlock focused on clarity, dilution control, and service precision.',
    status: 'ready',
    rewardPhase: 'midpoint',
    watermark: { enabled: false, label: 'KOOPE', placement: 'footer' },
    recipeIds: ['stirred-house-martini'],
    assetSlug: 'stirred-house-martini',
  },
  {
    id: 'unlock-techniques-dilution-control',
    moduleId: 'ch3-techniques-prep',
    lessonId: 'ch3-techniques-prep.lesson02',
    tier: 'FREE',
    format: 'mini_deck',
    kind: 'deck',
    assetName: 'Dilution Control',
    description: 'A field guide for reading chill, water, and texture before a drink goes flat or hot.',
    status: 'ready',
    rewardPhase: 'midpoint',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer' },
    assetSlug: 'dilution-control',
  },
  {
    id: 'unlock-techniques-shake-vs-stir',
    moduleId: 'ch3-techniques-prep',
    lessonId: 'ch3-techniques-prep.lesson01',
    tier: 'FREE',
    format: 'mini_deck',
    kind: 'deck',
    assetName: 'Shake vs Stir',
    description: 'A fast technique guide for choosing lift, integration, polish, and dilution control with intention.',
    status: 'ready',
    rewardPhase: 'midpoint',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer' },
    assetSlug: 'shake-vs-stir',
  },
  {
    id: 'unlock-techniques-syrup-deck',
    moduleId: 'ch3-techniques-prep',
    lessonId: 'ch3-techniques-prep.lesson05',
    tier: 'FREE',
    format: 'mini_deck',
    kind: 'deck',
    assetName: 'Simple Syrup + Rich Syrup Basics',
    description: 'A 3-5 slide prep deck covering syrup ratios, storage, and use cases.',
    status: 'ready',
    rewardPhase: 'late_module',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer' },
    assetSlug: 'simple-rich-syrup-basics',
  },
  {
    id: 'unlock-techniques-bitters-hack-guide',
    moduleId: 'ch3-techniques-prep',
    lessonId: 'ch3-techniques-prep.lesson06',
    tier: 'FREE',
    format: 'mini_deck',
    kind: 'deck',
    assetName: 'Bitters Hack Guide',
    description: 'A fast guide to using bitters for structure, finish, and small corrections.',
    status: 'ready',
    rewardPhase: 'late_module',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer' },
    assetSlug: 'bitters-hack-guide',
  },
  {
    id: 'unlock-techniques-syrup-storage',
    moduleId: 'ch3-techniques-prep',
    lessonId: 'ch3-techniques-prep.lesson05',
    tier: 'FREE',
    format: 'mini_deck',
    kind: 'deck',
    assetName: 'Syrup Storage & Shelf Life',
    description: 'A prep guide for keeping syrup stable, clean, and reliable longer.',
    status: 'ready',
    rewardPhase: 'late_module',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer' },
    assetSlug: 'syrup-storage-shelf-life',
  },
  {
    id: 'unlock-techniques-infusion-basics',
    moduleId: 'ch3-techniques-prep',
    lessonId: 'ch3-techniques-prep.lesson08',
    tier: 'FREE',
    format: 'mini_deck',
    kind: 'deck',
    assetName: 'Infusion Basics',
    description: 'A starter deck for choosing base spirit, timing, and restraint in clean infusions.',
    status: 'ready',
    rewardPhase: 'late_module',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer' },
    assetSlug: 'infusion-basics',
  },
  {
    id: 'unlock-techniques-checkpoint-card',
    moduleId: 'ch3-techniques-prep',
    lessonId: 'ch3-techniques-prep.lesson10',
    tier: 'FREE',
    format: 'premium_recipe_card',
    kind: 'recipe_card',
    assetName: 'Prep Room Gimlet',
    description: 'A polished checkpoint reward built around clean execution and prep discipline.',
    status: 'planned',
    rewardPhase: 'checkpoint',
    watermark: { enabled: true, label: 'KOOPE', placement: 'background' },
    assetSlug: 'prep-room-gimlet-card',
  },
  {
    id: 'unlock-classics-boulevardier',
    moduleId: 'ch5-classics-remix',
    lessonId: 'ch5-classics-remix.lesson02',
    tier: 'FREE',
    format: 'standard_recipe',
    kind: 'recipe',
    assetName: 'Boulevardier',
    description: 'A classic family unlock that reinforces substitution and spirit-forward structure.',
    status: 'ready',
    rewardPhase: 'midpoint',
    watermark: { enabled: false, label: 'KOOPE', placement: 'footer' },
    recipeIds: ['boulevardier'],
    assetSlug: 'boulevardier',
  },
  {
    id: 'unlock-classics-collins',
    moduleId: 'ch5-classics-remix',
    lessonId: 'ch5-classics-remix.lesson06',
    tier: 'FREE',
    format: 'standard_recipe',
    kind: 'recipe',
    assetName: 'Tom Collins House Spec',
    description: 'A template-driven reward that encourages users to read and build cocktail families.',
    status: 'ready',
    rewardPhase: 'late_module',
    watermark: { enabled: false, label: 'KOOPE', placement: 'footer' },
    recipeIds: ['tom-collins-house-spec'],
    assetSlug: 'tom-collins-house-spec',
  },
  {
    id: 'unlock-classics-daiquiri-riff-card',
    moduleId: 'ch5-classics-remix',
    lessonId: 'ch5-classics-remix.lesson09',
    tier: 'FREE',
    format: 'premium_recipe_card',
    kind: 'recipe_card',
    assetName: 'Modern Daiquiri Riff',
    description: 'A collectible card that rewards structure-based creativity instead of rote memorization.',
    status: 'planned',
    rewardPhase: 'late_module',
    watermark: { enabled: true, label: 'KOOPE', placement: 'background' },
    assetSlug: 'modern-daiquiri-riff-card',
  },
  {
    id: 'unlock-classics-citrus-balance-fixes',
    moduleId: 'ch5-classics-remix',
    lessonId: 'ch5-classics-remix.lesson04',
    tier: 'FREE',
    format: 'mini_deck',
    kind: 'deck',
    assetName: 'Citrus Balance Fixes',
    description: 'A corrective guide for dealing with drinks that read too sharp, too sweet, or structurally off.',
    status: 'ready',
    rewardPhase: 'midpoint',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer' },
    assetSlug: 'citrus-balance-fixes',
  },
  {
    id: 'unlock-classics-unbalanced-cocktail',
    moduleId: 'ch5-classics-remix',
    lessonId: 'ch5-classics-remix.lesson07',
    tier: 'FREE',
    format: 'mini_deck',
    kind: 'deck',
    assetName: 'How to Fix an Unbalanced Cocktail',
    description: 'A diagnostic deck for correcting drinks by pressure point instead of random adjustment.',
    status: 'ready',
    rewardPhase: 'late_module',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer' },
    assetSlug: 'how-to-fix-an-unbalanced-cocktail',
  },
  {
    id: 'unlock-classics-substitutions',
    moduleId: 'ch5-classics-remix',
    lessonId: 'ch5-classics-remix.lesson08',
    tier: 'FREE',
    format: 'mini_deck',
    kind: 'deck',
    assetName: 'Home Bar Emergency Substitutions',
    description: 'A remix guide for making smart swaps when a bottle, citrus, syrup, or modifier is missing.',
    status: 'ready',
    rewardPhase: 'late_module',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer' },
    assetSlug: 'home-bar-emergency-substitutions',
  },
  {
    id: 'unlock-classics-checkpoint-card',
    moduleId: 'ch5-classics-remix',
    lessonId: 'ch5-classics-remix.lesson10',
    tier: 'FREE',
    format: 'premium_recipe_card',
    kind: 'recipe_card',
    assetName: 'House Margarita Remix',
    description: 'Checkpoint reward for proving users can defend a drink structure, not just recognize one.',
    status: 'planned',
    rewardPhase: 'checkpoint',
    watermark: { enabled: true, label: 'KOOPE', placement: 'background' },
    assetSlug: 'house-margarita-remix-card',
  },
  {
    id: 'unlock-flavor-highball',
    moduleId: 'ch6-flavor-logic',
    lessonId: 'ch6-flavor-logic.lesson02',
    tier: 'FREE',
    format: 'standard_recipe',
    kind: 'recipe',
    assetName: 'Salted Citrus Highball',
    description: 'A practical reward for users learning how salt, acid, and dilution interact.',
    status: 'ready',
    rewardPhase: 'midpoint',
    watermark: { enabled: false, label: 'KOOPE', placement: 'footer' },
    recipeIds: ['salted-citrus-highball'],
    assetSlug: 'salted-citrus-highball',
  },
  {
    id: 'unlock-flavor-citrus-pairings',
    moduleId: 'ch6-flavor-logic',
    lessonId: 'ch6-flavor-logic.lesson03',
    tier: 'FREE',
    format: 'mini_deck',
    kind: 'deck',
    assetName: 'Flavor Bible: Citrus Pairings',
    description: 'A fast flavor reference for matching citrus styles to spirits, sweetness, and overall drink direction.',
    status: 'ready',
    rewardPhase: 'midpoint',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer' },
    assetSlug: 'flavor-bible-citrus-pairings',
  },
  {
    id: 'unlock-flavor-texture-hacks',
    moduleId: 'ch6-flavor-logic',
    lessonId: 'ch6-flavor-logic.lesson04',
    tier: 'FREE',
    format: 'mini_deck',
    kind: 'deck',
    assetName: 'Texture Hacks',
    description: 'A practical guide for using dilution, syrup weight, foam, and temperature to shape mouthfeel.',
    status: 'ready',
    rewardPhase: 'midpoint',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer' },
    assetSlug: 'texture-hacks',
  },
  {
    id: 'unlock-flavor-pairing-matrix',
    moduleId: 'ch6-flavor-logic',
    lessonId: 'ch6-flavor-logic.lesson05',
    tier: 'FREE',
    format: 'mini_deck',
    kind: 'deck',
    assetName: 'Easy Flavor Pairing Matrix',
    description: 'A practical field guide for pairing backbone, acid, sweetener, and modifier without guessing.',
    status: 'ready',
    rewardPhase: 'late_module',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer' },
    assetSlug: 'easy-flavor-pairing-matrix',
  },
  {
    id: 'unlock-flavor-seasonal-riff',
    moduleId: 'ch6-flavor-logic',
    lessonId: 'ch6-flavor-logic.lesson08',
    tier: 'FREE',
    format: 'mini_deck',
    kind: 'deck',
    assetName: 'Seasonal Riff Build Sheet',
    description: 'A slide deck that turns seasonal flavor design into a repeatable build system.',
    status: 'ready',
    rewardPhase: 'late_module',
    watermark: { enabled: true, label: 'KOOPE', placement: 'footer' },
    assetSlug: 'seasonal-riff-build-sheet',
  },
  {
    id: 'unlock-flavor-herb-pairings',
    moduleId: 'ch6-flavor-logic',
    lessonId: 'ch6-flavor-logic.lesson07',
    tier: 'FREE',
    format: 'mini_deck',
    kind: 'deck',
    assetName: 'Flavor Bible: Herb Pairings',
    description: 'A flavor reference for matching herbs to spirits, citrus, sweetness, and aromatic direction.',
    status: 'ready',
    rewardPhase: 'late_module',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer' },
    assetSlug: 'flavor-bible-herb-pairings',
  },
  {
    id: 'unlock-flavor-advanced-balance',
    moduleId: 'ch4-spirits-pairing',
    lessonId: 'ch4-spirits-pairing.lesson06',
    tier: 'PRO',
    format: 'mini_deck',
    kind: 'deck',
    assetName: 'Advanced Balance: Sweetness vs Weight',
    description: 'A mastery deck for separating sweetness level from body, weight, and perceived heaviness.',
    status: 'ready',
    rewardPhase: 'late_module',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer', tierBadge: 'PRO' },
    assetSlug: 'advanced-balance-sweetness-vs-weight',
  },
  {
    id: 'unlock-flavor-gimlet',
    moduleId: 'ch6-flavor-logic',
    lessonId: 'ch6-flavor-logic.lesson10',
    tier: 'FREE',
    format: 'premium_recipe_card',
    kind: 'recipe_card',
    assetName: 'Gimlet',
    description: 'Checkpoint reward for proving users can build and defend a balanced spec.',
    status: 'ready',
    rewardPhase: 'checkpoint',
    watermark: { enabled: true, label: 'KOOPE', placement: 'background' },
    recipeIds: ['gimlet'],
    assetSlug: 'gimlet-premium-card',
    notes: 'This is the first live unlock already wired into lesson completion.',
  },
  {
    id: 'unlock-mocktails-tea-citrus',
    moduleId: 'ch7-mocktails-zero-proof',
    lessonId: 'ch7-mocktails-zero-proof.lesson02',
    tier: 'FREE',
    format: 'standard_recipe',
    kind: 'recipe',
    assetName: 'Tea Citrus Cooler',
    description: 'A practical zero-proof spec that reinforces structure and acid balance.',
    status: 'ready',
    rewardPhase: 'midpoint',
    watermark: { enabled: false, label: 'KOOPE', placement: 'footer' },
    recipeIds: ['tea-citrus-cooler'],
    assetSlug: 'tea-citrus-cooler',
  },
  {
    id: 'unlock-mocktails-ginger-sparkler',
    moduleId: 'ch7-mocktails-zero-proof',
    lessonId: 'ch7-mocktails-zero-proof.lesson04',
    tier: 'FREE',
    format: 'standard_recipe',
    kind: 'recipe',
    assetName: 'Ginger Mint Sparkler',
    description: 'A structured NA reward that teaches syrup layering without relying on sugar alone.',
    status: 'ready',
    rewardPhase: 'late_module',
    watermark: { enabled: false, label: 'KOOPE', placement: 'footer' },
    recipeIds: ['ginger-mint-sparkler'],
    assetSlug: 'ginger-mint-sparkler',
  },
  {
    id: 'unlock-mocktails-presentation-guide',
    moduleId: 'ch7-mocktails-zero-proof',
    lessonId: 'ch7-mocktails-zero-proof.lesson08',
    tier: 'FREE',
    format: 'mini_deck',
    kind: 'deck',
    assetName: 'Build Better Mocktails',
    description: 'A zero-proof structure deck for body, aroma, acid, and finish so NA drinks feel complete instead of compensating.',
    status: 'ready',
    rewardPhase: 'late_module',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer' },
    assetSlug: 'build-better-mocktails',
  },
  {
    id: 'unlock-mocktails-hosting-hacks',
    moduleId: 'ch7-mocktails-zero-proof',
    lessonId: 'ch7-mocktails-zero-proof.lesson09',
    tier: 'FREE',
    format: 'mini_deck',
    kind: 'deck',
    assetName: 'Low-Effort High-Impact Hosting Hacks',
    description: 'A hosting deck for making the room feel cared for with better staging, pacing, and drink presentation.',
    status: 'ready',
    rewardPhase: 'late_module',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer' },
    assetSlug: 'low-effort-high-impact-hosting-hacks',
  },
  {
    id: 'unlock-mocktails-checkpoint-card',
    moduleId: 'ch7-mocktails-zero-proof',
    lessonId: 'ch7-mocktails-zero-proof.lesson10',
    tier: 'FREE',
    format: 'premium_recipe_card',
    kind: 'recipe_card',
    assetName: 'Signature Zero-Proof Spritz',
    description: 'Checkpoint reward for turning zero-proof structure into a finished signature serve.',
    status: 'planned',
    rewardPhase: 'checkpoint',
    watermark: { enabled: true, label: 'KOOPE', placement: 'background' },
    assetSlug: 'signature-zero-proof-spritz-card',
  },
  {
    id: 'unlock-batching-negroni',
    moduleId: 'ch5b-batching-punches',
    lessonId: 'ch5b-batching-punches.lesson01',
    tier: 'FREE',
    format: 'standard_recipe',
    kind: 'recipe',
    assetName: 'Party Negroni Batch',
    description: 'A practical scaled spec that rewards users for understanding batching math and service efficiency.',
    status: 'ready',
    rewardPhase: 'midpoint',
    watermark: { enabled: false, label: 'KOOPE', placement: 'footer' },
    recipeIds: ['party-negroni-batch'],
    assetSlug: 'party-negroni-batch',
  },
  {
    id: 'unlock-batching-scale-guide',
    moduleId: 'ch5b-batching-punches',
    lessonId: 'ch5b-batching-punches.lesson06',
    tier: 'FREE',
    format: 'mini_deck',
    kind: 'deck',
    assetName: 'Batching for 4, 8, and 12 Guests',
    description: 'A hosting deck for scaling drinks cleanly without losing balance or service rhythm.',
    status: 'ready',
    rewardPhase: 'midpoint',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer' },
    assetSlug: 'batching-for-4-8-and-12-guests',
  },
  {
    id: 'unlock-batching-citrus-punch',
    moduleId: 'ch5b-batching-punches',
    lessonId: 'ch5b-batching-punches.lesson04',
    tier: 'FREE',
    format: 'mini_deck',
    kind: 'deck',
    assetName: '10-Guest Citrus Punch',
    description: 'A hosting deck with full build, dilution, garnish, and service notes.',
    status: 'ready',
    rewardPhase: 'late_module',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer' },
    assetSlug: '10-guest-citrus-punch',
  },
  {
    id: 'unlock-batching-low-abv-punch',
    moduleId: 'ch5b-batching-punches',
    lessonId: 'ch5b-batching-punches.lesson07',
    tier: 'FREE',
    format: 'mini_deck',
    kind: 'deck',
    assetName: 'Low-ABV Hosting Punch',
    description: 'An inclusive punch deck built for event pacing and mixed guest preferences.',
    status: 'ready',
    rewardPhase: 'late_module',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer' },
    assetSlug: 'low-abv-hosting-punch',
  },
  {
    id: 'unlock-batching-party-punch-hacks',
    moduleId: 'ch5b-batching-punches',
    lessonId: 'ch5b-batching-punches.lesson08',
    tier: 'FREE',
    format: 'mini_deck',
    kind: 'deck',
    assetName: 'Party Punch Hacks',
    description: 'A fast hosting deck for keeping a larger-format punch fresh, social, and easy to manage through the night.',
    status: 'ready',
    rewardPhase: 'late_module',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer' },
    assetSlug: 'party-punch-hacks',
  },
  {
    id: 'unlock-batching-checkpoint-card',
    moduleId: 'ch5b-batching-punches',
    lessonId: 'ch5b-batching-punches.lesson10',
    tier: 'FREE',
    format: 'premium_recipe_card',
    kind: 'recipe_card',
    assetName: "Host's Signature Punch",
    description: 'Checkpoint reward for proving the user can design around event constraints, not just flavor.',
    status: 'planned',
    rewardPhase: 'checkpoint',
    watermark: { enabled: true, label: 'KOOPE', placement: 'background' },
    assetSlug: 'hosts-signature-punch-card',
  },
  {
    id: 'unlock-global-spritz-variant',
    moduleId: 'ch6-hosting-vibes',
    lessonId: 'ch6-hosting-vibes.lesson01',
    tier: 'PLUS',
    format: 'standard_recipe',
    kind: 'recipe',
    assetName: 'Aperitivo Spritz Variant',
    description: 'PLUS breadth reward tied to global style recognition and aperitivo culture.',
    status: 'ready',
    rewardPhase: 'midpoint',
    watermark: { enabled: false, label: 'KOOPE', placement: 'footer', tierBadge: 'PLUS' },
    recipeIds: ['aperitivo-spritz-variant'],
    assetSlug: 'aperitivo-spritz-variant',
  },
  {
    id: 'unlock-global-premium-look',
    moduleId: 'ch6-hosting-vibes',
    lessonId: 'ch6-hosting-vibes.lesson03',
    tier: 'PLUS',
    format: 'mini_deck',
    kind: 'deck',
    assetName: 'How to Make Drinks Look Premium',
    description: 'A presentation deck for making home drinks look intentional, refined, and worth serving proudly.',
    status: 'ready',
    rewardPhase: 'midpoint',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer', tierBadge: 'PLUS' },
    assetSlug: 'how-to-make-drinks-look-premium',
  },
  {
    id: 'unlock-global-latin-card',
    moduleId: 'ch6-hosting-vibes',
    lessonId: 'ch6-hosting-vibes.lesson04',
    tier: 'PLUS',
    format: 'premium_recipe_card',
    kind: 'recipe_card',
    assetName: 'Latin Citrus Cooler',
    description: 'A collectible card reward for Latin American cocktail structure and flavor memory.',
    status: 'planned',
    rewardPhase: 'late_module',
    watermark: { enabled: true, label: 'KOOPE', placement: 'background', tierBadge: 'PLUS' },
    assetSlug: 'latin-citrus-cooler-card',
  },
  {
    id: 'unlock-global-tiki-card',
    moduleId: 'ch6-hosting-vibes',
    lessonId: 'ch6-hosting-vibes.lesson08',
    tier: 'PLUS',
    format: 'premium_recipe_card',
    kind: 'recipe_card',
    assetName: 'Tiki House Serve',
    description: 'A premium global reward that leans into tropical identity and presentation.',
    status: 'planned',
    rewardPhase: 'late_module',
    watermark: { enabled: true, label: 'KOOPE', placement: 'background', tierBadge: 'PLUS' },
    assetSlug: 'tiki-house-serve-card',
  },
  {
    id: 'unlock-global-tour-pack',
    moduleId: 'ch6-hosting-vibes',
    lessonId: 'ch6-hosting-vibes.lesson10',
    tier: 'PLUS',
    format: 'mini_deck',
    kind: 'deck',
    assetName: 'Global Tour Recipe Pack',
    description: 'A multi-slide regional reward pack that feels broader than a single recipe.',
    status: 'ready',
    rewardPhase: 'checkpoint',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer', tierBadge: 'PLUS' },
    assetSlug: 'global-tour-recipe-pack',
  },
  {
    id: 'unlock-global-speed-garnish',
    moduleId: 'ch6-hosting-vibes',
    lessonId: 'ch6-hosting-vibes.lesson08',
    tier: 'PLUS',
    format: 'mini_deck',
    kind: 'deck',
    assetName: 'Speed Garnish Moves',
    description: 'A presentation deck for faster garnish execution that still feels sharp and considered.',
    status: 'ready',
    rewardPhase: 'late_module',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer', tierBadge: 'PLUS' },
    assetSlug: 'speed-garnish-moves',
  },
  {
    id: 'unlock-mastery-old-fashioned',
    moduleId: 'ch4-spirits-pairing',
    lessonId: 'ch4-spirits-pairing.lesson02',
    tier: 'PRO',
    format: 'standard_recipe',
    kind: 'recipe',
    assetName: 'Barrel-Driven Old Fashioned',
    description: 'A PRO unlock that links aging knowledge to a refined, spirit-led spec.',
    status: 'ready',
    rewardPhase: 'midpoint',
    watermark: { enabled: false, label: 'KOOPE', placement: 'footer', tierBadge: 'PRO' },
    recipeIds: ['barrel-driven-old-fashioned'],
    assetSlug: 'barrel-driven-old-fashioned',
  },
  {
    id: 'unlock-mastery-label-reading',
    moduleId: 'ch4-spirits-pairing',
    lessonId: 'ch4-spirits-pairing.lesson09',
    tier: 'PRO',
    format: 'mini_deck',
    kind: 'deck',
    assetName: 'Label Reading Like a Pro',
    description: 'A mastery deck for decoding bottle cues, production language, and what a label really tells you.',
    status: 'ready',
    rewardPhase: 'late_module',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer', tierBadge: 'PRO' },
    assetSlug: 'label-reading-like-a-pro',
  },
  {
    id: 'unlock-mastery-fortified-wine-hacks',
    moduleId: 'ch4-spirits-pairing',
    lessonId: 'ch4-spirits-pairing.lesson04',
    tier: 'PRO',
    format: 'mini_deck',
    kind: 'deck',
    assetName: 'Fortified Wine Hacks',
    description: 'A mastery deck for using vermouth, sherry, and fortified wines with more precision and confidence.',
    status: 'ready',
    rewardPhase: 'late_module',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer', tierBadge: 'PRO' },
    assetSlug: 'fortified-wine-hacks',
  },
  {
    id: 'unlock-mastery-gin-botanicals',
    moduleId: 'ch4-spirits-pairing',
    lessonId: 'ch4-spirits-pairing.lesson05',
    tier: 'PRO',
    format: 'mini_deck',
    kind: 'deck',
    assetName: 'Gin Botanical Comparison Card',
    description: 'A premium tasting deck for comparing botanical architecture and cocktail fit.',
    status: 'ready',
    rewardPhase: 'late_module',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer', tierBadge: 'PRO' },
    assetSlug: 'gin-botanical-comparison-card',
  },
  {
    id: 'unlock-mastery-bitter-tincture-basics',
    moduleId: 'ch4-spirits-pairing',
    lessonId: 'ch4-spirits-pairing.lesson07',
    tier: 'PRO',
    format: 'mini_deck',
    kind: 'deck',
    assetName: 'Bitter & Tincture Basics',
    description: 'A technical deck for using bittering agents and tinctures to add precision, finish, and structure.',
    status: 'ready',
    rewardPhase: 'late_module',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer', tierBadge: 'PRO' },
    assetSlug: 'bitter-and-tincture-basics',
  },
  {
    id: 'unlock-mastery-modifier-notes',
    moduleId: 'ch4-spirits-pairing',
    lessonId: 'ch4-spirits-pairing.lesson08',
    tier: 'PRO',
    format: 'mini_deck',
    kind: 'deck',
    assetName: 'Modifier and Liqueur Build Notes',
    description: 'A technical deck covering how modifiers shape sweetness, bitterness, and identity.',
    status: 'ready',
    rewardPhase: 'late_module',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer', tierBadge: 'PRO' },
    assetSlug: 'modifier-and-liqueur-build-notes',
  },
  {
    id: 'unlock-mastery-taste-spirits',
    moduleId: 'ch4-spirits-pairing',
    lessonId: 'ch4-spirits-pairing.lesson03',
    tier: 'PRO',
    format: 'mini_deck',
    kind: 'deck',
    assetName: 'Taste Spirits Like a Pro',
    description: 'A tasting framework for separating aroma, structure, finish, and cocktail fit like a professional.',
    status: 'ready',
    rewardPhase: 'late_module',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer', tierBadge: 'PRO' },
    assetSlug: 'taste-spirits-like-a-pro',
  },
  {
    id: 'unlock-mastery-checkpoint-card',
    moduleId: 'ch4-spirits-pairing',
    lessonId: 'ch4-spirits-pairing.lesson10',
    tier: 'PRO',
    format: 'mixology_recipe_card',
    kind: 'recipe_card',
    assetName: "Distiller's Reserve Manhattan",
    description: 'Premium checkpoint reward for users who can read process, flavor, and label language at a deeper level.',
    status: 'planned',
    rewardPhase: 'checkpoint',
    watermark: { enabled: true, label: 'KOOPE', placement: 'background', tierBadge: 'PRO' },
    assetSlug: 'distillers-reserve-manhattan-card',
  },
];

export function getUnlocksForModule(moduleId?: string | null): CurriculumUnlock[] {
  if (!moduleId) return [];
  return CURRICULUM_UNLOCKS.filter((unlock) => unlock.moduleId === moduleId);
}

export function getUnlocksForLesson(lessonId?: string | null): CurriculumUnlock[] {
  if (!lessonId) return [];
  return CURRICULUM_UNLOCKS.filter((unlock) => unlock.lessonId === lessonId);
}

export function getReadyRecipeUnlocksForLesson(lessonId?: string | null): CurriculumUnlock[] {
  if (!lessonId) return [];
  return CURRICULUM_UNLOCKS.filter(
    (unlock) => unlock.lessonId === lessonId && unlock.status === 'ready' && Array.isArray(unlock.recipeIds) && unlock.recipeIds.length > 0
  );
}

export const CURRICULUM_UNLOCK_RECIPE_IDS = new Set(
  CURRICULUM_UNLOCKS.flatMap((unlock) => unlock.recipeIds || [])
);

export function isCurriculumUnlockRecipeId(recipeId?: string | null): boolean {
  if (!recipeId) return false;
  return CURRICULUM_UNLOCK_RECIPE_IDS.has(recipeId);
}

export function getCurriculumUnlockForRecipeId(recipeId?: string | null): CurriculumUnlock | undefined {
  if (!recipeId) return undefined;
  return CURRICULUM_UNLOCKS.find((unlock) => unlock.recipeIds?.includes(recipeId));
}

export function getUnlockByAssetSlug(assetSlug?: string | null): CurriculumUnlock | undefined {
  if (!assetSlug) return undefined;
  return CURRICULUM_UNLOCKS.find((unlock) => unlock.assetSlug === assetSlug);
}
