export type UnlockTier = 'FREE' | 'PLUS' | 'PRO';
export type UnlockFormat = 'standard_recipe' | 'premium_recipe_card' | 'mini_deck' | 'utility_card';
export type UnlockKind = 'recipe' | 'recipe_card' | 'deck' | 'utility';
export type UnlockStatus = 'planned' | 'ready';

export interface CurriculumUnlock {
  id: string;
  moduleId: string;
  lessonId: string;
  tier: UnlockTier;
  format: UnlockFormat;
  kind: UnlockKind;
  assetName: string;
  description: string;
  status: UnlockStatus;
  rewardPhase: 'midpoint' | 'late_module' | 'checkpoint' | 'module_completion';
  watermark: {
    enabled: boolean;
    label: string;
    placement: 'footer' | 'background';
    tierBadge?: UnlockTier;
  };
  recipeIds?: string[];
  assetSlug?: string;
  notes?: string;
}

export const CURRICULUM_UNLOCKS: CurriculumUnlock[] = [
  {
    id: 'unlock-basics-house-daiquiri',
    moduleId: 'ch1-bartending-basics',
    lessonId: 'ch1-bartending-basics.lesson03',
    tier: 'FREE',
    format: 'standard_recipe',
    kind: 'recipe',
    assetName: 'House Daiquiri Spec',
    description: 'A clean, foundational spec that rewards early confidence and teaches balance through simplicity.',
    status: 'ready',
    rewardPhase: 'midpoint',
    watermark: { enabled: false, label: 'KOOPE', placement: 'footer' },
    recipeIds: ['house-daiquiri-spec'],
    assetSlug: 'house-daiquiri-spec',
  },
  {
    id: 'unlock-basics-bar-setup-guide',
    moduleId: 'ch1-bartending-basics',
    lessonId: 'ch1-bartending-basics.lesson07',
    tier: 'FREE',
    format: 'utility_card',
    kind: 'utility',
    assetName: 'Bar Setup Quick Guide',
    description: 'A practical station-prep card users can reference before hosting or practice sessions.',
    status: 'planned',
    rewardPhase: 'late_module',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer' },
    assetSlug: 'bar-setup-quick-guide',
  },
  {
    id: 'unlock-basics-checkpoint-card',
    moduleId: 'ch1-bartending-basics',
    lessonId: 'ch1-bartending-basics.lesson10',
    tier: 'FREE',
    format: 'premium_recipe_card',
    kind: 'recipe_card',
    assetName: "Bartender's Lemon Sour",
    description: 'Checkpoint card reward for completing the fundamentals path with a practical, polished house-style serve.',
    status: 'planned',
    rewardPhase: 'checkpoint',
    watermark: { enabled: true, label: 'KOOPE', placement: 'background' },
    assetSlug: 'bartenders-lemon-sour-card',
  },
  {
    id: 'unlock-techniques-house-martini',
    moduleId: 'ch3-techniques-prep',
    lessonId: 'ch3-techniques-prep.lesson03',
    tier: 'FREE',
    format: 'standard_recipe',
    kind: 'recipe',
    assetName: 'Stirred House Martini',
    description: 'A technique-led unlock focused on clarity, dilution control, and service precision.',
    status: 'ready',
    rewardPhase: 'midpoint',
    watermark: { enabled: false, label: 'KOOPE', placement: 'footer' },
    recipeIds: ['stirred-house-martini'],
    assetSlug: 'stirred-house-martini',
  },
  {
    id: 'unlock-techniques-syrup-deck',
    moduleId: 'ch3-techniques-prep',
    lessonId: 'ch3-techniques-prep.lesson05',
    tier: 'FREE',
    format: 'mini_deck',
    kind: 'deck',
    assetName: 'Simple Syrup + Rich Syrup Basics',
    description: 'A 3-5 slide prep deck covering syrup ratios, storage, and use cases.',
    status: 'ready',
    rewardPhase: 'late_module',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer' },
    assetSlug: 'simple-rich-syrup-basics',
  },
  {
    id: 'unlock-techniques-checkpoint-card',
    moduleId: 'ch3-techniques-prep',
    lessonId: 'ch3-techniques-prep.lesson10',
    tier: 'FREE',
    format: 'premium_recipe_card',
    kind: 'recipe_card',
    assetName: 'Prep Room Gimlet',
    description: 'A polished checkpoint reward built around clean execution and prep discipline.',
    status: 'planned',
    rewardPhase: 'checkpoint',
    watermark: { enabled: true, label: 'KOOPE', placement: 'background' },
    assetSlug: 'prep-room-gimlet-card',
  },
  {
    id: 'unlock-classics-boulevardier',
    moduleId: 'ch5-classics-remix',
    lessonId: 'ch5-classics-remix.lesson02',
    tier: 'FREE',
    format: 'standard_recipe',
    kind: 'recipe',
    assetName: 'Boulevardier',
    description: 'A classic family unlock that reinforces substitution and spirit-forward structure.',
    status: 'ready',
    rewardPhase: 'midpoint',
    watermark: { enabled: false, label: 'KOOPE', placement: 'footer' },
    recipeIds: ['boulevardier'],
    assetSlug: 'boulevardier',
  },
  {
    id: 'unlock-classics-collins',
    moduleId: 'ch5-classics-remix',
    lessonId: 'ch5-classics-remix.lesson06',
    tier: 'FREE',
    format: 'standard_recipe',
    kind: 'recipe',
    assetName: 'Tom Collins House Spec',
    description: 'A template-driven reward that encourages users to read and build cocktail families.',
    status: 'ready',
    rewardPhase: 'late_module',
    watermark: { enabled: false, label: 'KOOPE', placement: 'footer' },
    recipeIds: ['tom-collins-house-spec'],
    assetSlug: 'tom-collins-house-spec',
  },
  {
    id: 'unlock-classics-daiquiri-riff-card',
    moduleId: 'ch5-classics-remix',
    lessonId: 'ch5-classics-remix.lesson09',
    tier: 'FREE',
    format: 'premium_recipe_card',
    kind: 'recipe_card',
    assetName: 'Modern Daiquiri Riff',
    description: 'A collectible card that rewards structure-based creativity instead of rote memorization.',
    status: 'planned',
    rewardPhase: 'late_module',
    watermark: { enabled: true, label: 'KOOPE', placement: 'background' },
    assetSlug: 'modern-daiquiri-riff-card',
  },
  {
    id: 'unlock-classics-checkpoint-card',
    moduleId: 'ch5-classics-remix',
    lessonId: 'ch5-classics-remix.lesson10',
    tier: 'FREE',
    format: 'premium_recipe_card',
    kind: 'recipe_card',
    assetName: 'House Margarita Remix',
    description: 'Checkpoint reward for proving users can defend a drink structure, not just recognize one.',
    status: 'planned',
    rewardPhase: 'checkpoint',
    watermark: { enabled: true, label: 'KOOPE', placement: 'background' },
    assetSlug: 'house-margarita-remix-card',
  },
  {
    id: 'unlock-flavor-highball',
    moduleId: 'ch6-flavor-logic',
    lessonId: 'ch6-flavor-logic.lesson02',
    tier: 'FREE',
    format: 'standard_recipe',
    kind: 'recipe',
    assetName: 'Salted Citrus Highball',
    description: 'A practical reward for users learning how salt, acid, and dilution interact.',
    status: 'ready',
    rewardPhase: 'midpoint',
    watermark: { enabled: false, label: 'KOOPE', placement: 'footer' },
    recipeIds: ['salted-citrus-highball'],
    assetSlug: 'salted-citrus-highball',
  },
  {
    id: 'unlock-flavor-pairing-matrix',
    moduleId: 'ch6-flavor-logic',
    lessonId: 'ch6-flavor-logic.lesson05',
    tier: 'FREE',
    format: 'mini_deck',
    kind: 'deck',
    assetName: 'Flavor Pairing Matrix',
    description: 'A reusable pairing deck mapping spirit, citrus, sweetener, and modifier logic.',
    status: 'planned',
    rewardPhase: 'late_module',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer' },
    assetSlug: 'flavor-pairing-matrix',
  },
  {
    id: 'unlock-flavor-seasonal-riff',
    moduleId: 'ch6-flavor-logic',
    lessonId: 'ch6-flavor-logic.lesson08',
    tier: 'FREE',
    format: 'mini_deck',
    kind: 'deck',
    assetName: 'Seasonal Riff Build Sheet',
    description: 'A slide deck that turns seasonal flavor design into a repeatable build system.',
    status: 'planned',
    rewardPhase: 'late_module',
    watermark: { enabled: true, label: 'KOOPE', placement: 'footer' },
    assetSlug: 'seasonal-riff-build-sheet',
  },
  {
    id: 'unlock-flavor-gimlet',
    moduleId: 'ch6-flavor-logic',
    lessonId: 'ch6-flavor-logic.lesson10',
    tier: 'FREE',
    format: 'premium_recipe_card',
    kind: 'recipe_card',
    assetName: 'Gimlet',
    description: 'Checkpoint reward for proving users can build and defend a balanced spec.',
    status: 'ready',
    rewardPhase: 'checkpoint',
    watermark: { enabled: true, label: 'KOOPE', placement: 'background' },
    recipeIds: ['gimlet'],
    assetSlug: 'gimlet-premium-card',
    notes: 'This is the first live unlock already wired into lesson completion.',
  },
  {
    id: 'unlock-mocktails-tea-citrus',
    moduleId: 'ch7-mocktails-zero-proof',
    lessonId: 'ch7-mocktails-zero-proof.lesson02',
    tier: 'FREE',
    format: 'standard_recipe',
    kind: 'recipe',
    assetName: 'Tea Citrus Cooler',
    description: 'A practical zero-proof spec that reinforces structure and acid balance.',
    status: 'ready',
    rewardPhase: 'midpoint',
    watermark: { enabled: false, label: 'KOOPE', placement: 'footer' },
    recipeIds: ['tea-citrus-cooler'],
    assetSlug: 'tea-citrus-cooler',
  },
  {
    id: 'unlock-mocktails-ginger-sparkler',
    moduleId: 'ch7-mocktails-zero-proof',
    lessonId: 'ch7-mocktails-zero-proof.lesson04',
    tier: 'FREE',
    format: 'standard_recipe',
    kind: 'recipe',
    assetName: 'Ginger Mint Sparkler',
    description: 'A structured NA reward that teaches syrup layering without relying on sugar alone.',
    status: 'ready',
    rewardPhase: 'late_module',
    watermark: { enabled: false, label: 'KOOPE', placement: 'footer' },
    recipeIds: ['ginger-mint-sparkler'],
    assetSlug: 'ginger-mint-sparkler',
  },
  {
    id: 'unlock-mocktails-presentation-guide',
    moduleId: 'ch7-mocktails-zero-proof',
    lessonId: 'ch7-mocktails-zero-proof.lesson08',
    tier: 'FREE',
    format: 'mini_deck',
    kind: 'deck',
    assetName: 'Premium Zero-Proof Presentation Guide',
    description: 'A visual deck for glassware, garnish, ice, and premium service presentation.',
    status: 'planned',
    rewardPhase: 'late_module',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer' },
    assetSlug: 'premium-zero-proof-presentation-guide',
  },
  {
    id: 'unlock-mocktails-checkpoint-card',
    moduleId: 'ch7-mocktails-zero-proof',
    lessonId: 'ch7-mocktails-zero-proof.lesson10',
    tier: 'FREE',
    format: 'premium_recipe_card',
    kind: 'recipe_card',
    assetName: 'Signature Zero-Proof Spritz',
    description: 'Checkpoint reward for turning zero-proof structure into a finished signature serve.',
    status: 'planned',
    rewardPhase: 'checkpoint',
    watermark: { enabled: true, label: 'KOOPE', placement: 'background' },
    assetSlug: 'signature-zero-proof-spritz-card',
  },
  {
    id: 'unlock-batching-negroni',
    moduleId: 'ch5b-batching-punches',
    lessonId: 'ch5b-batching-punches.lesson01',
    tier: 'FREE',
    format: 'standard_recipe',
    kind: 'recipe',
    assetName: 'Party Negroni Batch',
    description: 'A practical scaled spec that rewards users for understanding batching math and service efficiency.',
    status: 'ready',
    rewardPhase: 'midpoint',
    watermark: { enabled: false, label: 'KOOPE', placement: 'footer' },
    recipeIds: ['party-negroni-batch'],
    assetSlug: 'party-negroni-batch',
  },
  {
    id: 'unlock-batching-citrus-punch',
    moduleId: 'ch5b-batching-punches',
    lessonId: 'ch5b-batching-punches.lesson04',
    tier: 'FREE',
    format: 'mini_deck',
    kind: 'deck',
    assetName: '10-Guest Citrus Punch',
    description: 'A hosting deck with full build, dilution, garnish, and service notes.',
    status: 'planned',
    rewardPhase: 'late_module',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer' },
    assetSlug: '10-guest-citrus-punch',
  },
  {
    id: 'unlock-batching-low-abv-punch',
    moduleId: 'ch5b-batching-punches',
    lessonId: 'ch5b-batching-punches.lesson07',
    tier: 'FREE',
    format: 'mini_deck',
    kind: 'deck',
    assetName: 'Low-ABV Hosting Punch',
    description: 'An inclusive punch deck built for event pacing and mixed guest preferences.',
    status: 'planned',
    rewardPhase: 'late_module',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer' },
    assetSlug: 'low-abv-hosting-punch',
  },
  {
    id: 'unlock-batching-checkpoint-card',
    moduleId: 'ch5b-batching-punches',
    lessonId: 'ch5b-batching-punches.lesson10',
    tier: 'FREE',
    format: 'premium_recipe_card',
    kind: 'recipe_card',
    assetName: "Host's Signature Punch",
    description: 'Checkpoint reward for proving the user can design around event constraints, not just flavor.',
    status: 'planned',
    rewardPhase: 'checkpoint',
    watermark: { enabled: true, label: 'KOOPE', placement: 'background' },
    assetSlug: 'hosts-signature-punch-card',
  },
  {
    id: 'unlock-global-spritz-variant',
    moduleId: 'ch6-hosting-vibes',
    lessonId: 'ch6-hosting-vibes.lesson01',
    tier: 'PLUS',
    format: 'standard_recipe',
    kind: 'recipe',
    assetName: 'Aperitivo Spritz Variant',
    description: 'PLUS breadth reward tied to global style recognition and aperitivo culture.',
    status: 'ready',
    rewardPhase: 'midpoint',
    watermark: { enabled: false, label: 'KOOPE', placement: 'footer', tierBadge: 'PLUS' },
    recipeIds: ['aperitivo-spritz-variant'],
    assetSlug: 'aperitivo-spritz-variant',
  },
  {
    id: 'unlock-global-latin-card',
    moduleId: 'ch6-hosting-vibes',
    lessonId: 'ch6-hosting-vibes.lesson04',
    tier: 'PLUS',
    format: 'premium_recipe_card',
    kind: 'recipe_card',
    assetName: 'Latin Citrus Cooler',
    description: 'A collectible card reward for Latin American cocktail structure and flavor memory.',
    status: 'planned',
    rewardPhase: 'late_module',
    watermark: { enabled: true, label: 'KOOPE', placement: 'background', tierBadge: 'PLUS' },
    assetSlug: 'latin-citrus-cooler-card',
  },
  {
    id: 'unlock-global-tiki-card',
    moduleId: 'ch6-hosting-vibes',
    lessonId: 'ch6-hosting-vibes.lesson08',
    tier: 'PLUS',
    format: 'premium_recipe_card',
    kind: 'recipe_card',
    assetName: 'Tiki House Serve',
    description: 'A premium global reward that leans into tropical identity and presentation.',
    status: 'planned',
    rewardPhase: 'late_module',
    watermark: { enabled: true, label: 'KOOPE', placement: 'background', tierBadge: 'PLUS' },
    assetSlug: 'tiki-house-serve-card',
  },
  {
    id: 'unlock-global-tour-pack',
    moduleId: 'ch6-hosting-vibes',
    lessonId: 'ch6-hosting-vibes.lesson10',
    tier: 'PLUS',
    format: 'mini_deck',
    kind: 'deck',
    assetName: 'Global Tour Recipe Pack',
    description: 'A multi-slide regional reward pack that feels broader than a single recipe.',
    status: 'planned',
    rewardPhase: 'checkpoint',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer', tierBadge: 'PLUS' },
    assetSlug: 'global-tour-recipe-pack',
  },
  {
    id: 'unlock-mastery-old-fashioned',
    moduleId: 'ch4-spirits-pairing',
    lessonId: 'ch4-spirits-pairing.lesson02',
    tier: 'PRO',
    format: 'standard_recipe',
    kind: 'recipe',
    assetName: 'Barrel-Driven Old Fashioned',
    description: 'A PRO unlock that links aging knowledge to a refined, spirit-led spec.',
    status: 'ready',
    rewardPhase: 'midpoint',
    watermark: { enabled: false, label: 'KOOPE', placement: 'footer', tierBadge: 'PRO' },
    recipeIds: ['barrel-driven-old-fashioned'],
    assetSlug: 'barrel-driven-old-fashioned',
  },
  {
    id: 'unlock-mastery-gin-botanicals',
    moduleId: 'ch4-spirits-pairing',
    lessonId: 'ch4-spirits-pairing.lesson05',
    tier: 'PRO',
    format: 'mini_deck',
    kind: 'deck',
    assetName: 'Gin Botanical Comparison Card',
    description: 'A premium tasting deck for comparing botanical architecture and cocktail fit.',
    status: 'planned',
    rewardPhase: 'late_module',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer', tierBadge: 'PRO' },
    assetSlug: 'gin-botanical-comparison-card',
  },
  {
    id: 'unlock-mastery-modifier-notes',
    moduleId: 'ch4-spirits-pairing',
    lessonId: 'ch4-spirits-pairing.lesson08',
    tier: 'PRO',
    format: 'mini_deck',
    kind: 'deck',
    assetName: 'Modifier and Liqueur Build Notes',
    description: 'A technical deck covering how modifiers shape sweetness, bitterness, and identity.',
    status: 'planned',
    rewardPhase: 'late_module',
    watermark: { enabled: true, label: 'Unlocked in KOOPE', placement: 'footer', tierBadge: 'PRO' },
    assetSlug: 'modifier-and-liqueur-build-notes',
  },
  {
    id: 'unlock-mastery-checkpoint-card',
    moduleId: 'ch4-spirits-pairing',
    lessonId: 'ch4-spirits-pairing.lesson10',
    tier: 'PRO',
    format: 'premium_recipe_card',
    kind: 'recipe_card',
    assetName: "Distiller's Reserve Manhattan",
    description: 'Premium checkpoint reward for users who can read process, flavor, and label language at a deeper level.',
    status: 'planned',
    rewardPhase: 'checkpoint',
    watermark: { enabled: true, label: 'KOOPE', placement: 'background', tierBadge: 'PRO' },
    assetSlug: 'distillers-reserve-manhattan-card',
  },
];

export function getUnlocksForModule(moduleId?: string | null): CurriculumUnlock[] {
  if (!moduleId) return [];
  return CURRICULUM_UNLOCKS.filter((unlock) => unlock.moduleId === moduleId);
}

export function getUnlocksForLesson(lessonId?: string | null): CurriculumUnlock[] {
  if (!lessonId) return [];
  return CURRICULUM_UNLOCKS.filter((unlock) => unlock.lessonId === lessonId);
}

export function getReadyRecipeUnlocksForLesson(lessonId?: string | null): CurriculumUnlock[] {
  if (!lessonId) return [];
  return CURRICULUM_UNLOCKS.filter(
    (unlock) => unlock.lessonId === lessonId && unlock.status === 'ready' && Array.isArray(unlock.recipeIds) && unlock.recipeIds.length > 0
  );
}

export const CURRICULUM_UNLOCK_RECIPE_IDS = new Set(
  CURRICULUM_UNLOCKS.flatMap((unlock) => unlock.recipeIds || [])
);

export function isCurriculumUnlockRecipeId(recipeId?: string | null): boolean {
  if (!recipeId) return false;
  return CURRICULUM_UNLOCK_RECIPE_IDS.has(recipeId);
}

export function getCurriculumUnlockForRecipeId(recipeId?: string | null): CurriculumUnlock | undefined {
  if (!recipeId) return undefined;
  return CURRICULUM_UNLOCKS.find((unlock) => unlock.recipeIds?.includes(recipeId));
}

export function getUnlockByAssetSlug(assetSlug?: string | null): CurriculumUnlock | undefined {
  if (!assetSlug) return undefined;
  return CURRICULUM_UNLOCKS.find((unlock) => unlock.assetSlug === assetSlug);
}
